version: '3.8'

services:
    app:
        build:
            context: .
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - app_network
        environment:
            - APP_ENV=production
            - APP_KEY=
            - DB_HOST=
            - DB_PORT=3306
            - DB_DATABASE=
            - DB_USERNAME=
            - DB_PASSWORD=
        command: ["sh", "./start.sh"]

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app_network
        depends_on:
            - app

networks:
    app_network:
        driver: bridge

volumes:
    db_data:
